# Site settings
title:       CS-JEDI
author:      a
baseurl:     "/~15996"
url:         "https://cs.cmu.edu"
header_pages:
  - pedag_found.md
  - library.md 
  - public_materials.md
  - faqs.md
keywords: []

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data', 'strikethrough']
permalink:    pretty
sass:
  style: compressed
  sass_dir: _sass
plugins:
  - jekyll-sitemap
  - jekyll-last-modified-at
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - CNAME

blank-link: ""



canvas-link: "https://canvas.cmu.edu/courses/39612"
syllabus-link: "https://docs.google.com/document/d/1XJFxkp0ZVXT5jmBcX-_ayng_IJJ5ry_a/edit?usp=drive_link&ouid=105057888275073041046&rtpof=true&sd=true"
anonymous-feedback-link: "https://docs.google.com/forms/d/e/1FAIpQLSdmooikaOqCNDWSAT_Mmf4PSeTivR0TGAxSyeqCmRZsYezI1g/viewform?usp=sf_link" 
google-drive-link: "https://drive.google.com/drive/folders/1wV2-JTVgA1G85blNRzxu7UCT9lLk-cD6?usp=sharing"
discussion-guide-link: "https://docs.google.com/document/d/1cCPyefNz-RGaO6eco4RYKUxR6NBRRufP/edit?usp=drive_link&ouid=105057888275073041046&rtpof=true&sd=true"
groups-and-lenses-link: "https://docs.google.com/spreadsheets/d/1fm121ADencuwKNBFFG0jw7-xUt8VXfWE0Aa71w6HiQg/edit?usp=drive_link"
project-overview-link: "https://docs.google.com/document/d/1bwp4ln4IMQFHdy0sACINZmYa76-zNDdX/edit?usp=drive_link&ouid=105057888275073041046&rtpof=true&sd=true"
glossary-link: "https://docs.google.com/document/d/1cyokGZWFP3eTexk9GWNJCofc13l89Lrb/edit?usp=drive_link&ouid=105057888275073041046&rtpof=true&sd=true"
library-link: "https://docs.google.com/spreadsheets/d/1fIZ_Jk95J4ZjMw37tsLmqemLTUplo3BzfVrmmqMDM4A/edit?usp=share_link"
schedules-link: "https://docs.google.com/document/d/1cCsLF2AXTgyju-hwfNYt8WYA_sG-S8Cv/edit?usp=drive_link&ouid=105057888275073041046&rtpof=true&sd=true"
make-up-link: "https://docs.google.com/document/d/1dRerarmJGguYHDjC5tixTczIYtoJu29n/edit?usp=drive_link&ouid=105057888275073041046&rtpof=true&sd=true"
supportive-resources-link: "https://docs.google.com/document/d/1d3SxOqQQuPup6PrUviJ90QytcbEzOO8u/edit?usp=drive_link&ouid=105057888275073041046&rtpof=true&sd=true"
get-involved-link: "https://docs.google.com/document/d/1cT_iDxSr3jDpjAJTUnkShRrMFyuoANkP/edit?usp=drive_link&ouid=105057888275073041046&rtpof=true&sd=true"

pre-class-1-link: "https://docs.google.com/document/d/1cqL857CoC6uBMpcCPZo_MEullmIXPFQv/edit?usp=drive_link&ouid=105057888275073041046&rtpof=true&sd=true"
pre-class-2-link: "https://docs.google.com/document/d/1cwS5Z1Yt-CE7FXO_Y4awyTplUjJ0YAAf/edit?usp=drive_link&ouid=105057888275073041046&rtpof=true&sd=true"
pre-class-3-link: "https://docs.google.com/document/d/1cVybJc0CMqkRqKSfvpEhjuetabQi4CGN/edit?usp=sharing&ouid=105057888275073041046&rtpof=true&sd=true"
pre-class-4-link: "https://docs.google.com/document/d/1cuidl13FbivNKgyUM2Xz9-bfRpNWCPr6/edit?usp=sharing&ouid=105057888275073041046&rtpof=true&sd=true"
pre-class-5-link: "https://docs.google.com/document/d/1cntVen2JiY9GSyMuP1SziCMZTXlqnkiO/edit?usp=sharing&ouid=105057888275073041046&rtpof=true&sd=true"
pre-class-6-link: "https://docs.google.com/document/d/1cn2NtWxShoOAqQ43TojbaqRk5DyC9bv5/edit?usp=sharing&ouid=105057888275073041046&rtpof=true&sd=true"
post-class-link: "https://docs.google.com/document/d/1Gl_A7OcriQsijHG2SL6R9LUPUeWfwyBPIQZiwlTpBL0/edit?usp=drive_link"


lec-slides-1-link: ""
lec-slides-2-link: ""
lec-slides-3-link: ""
lec-slides-4-link: ""
lec-slides-5-link: ""
lec-slides-6-link: ""

